[package]
name = "bounding_curve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = {version = "1.5.1", features = ["derive"]}

[dev-dependencies]
libfuzzer-sys = "0.4.7"
rand = "0.8.5"
